const ROLES = Object.freeze({
  MEMBRE: "MEMBRE",
  ADMINISTRATEUR: "ADMINISTRATEUR",
  CHEF_LABO: "CHEF_LABO",
});

const ACCOUNT_STATUS = Object.freeze({
  EN_ATTENTE: "EN_ATTENTE",
  ACTIF: "ACTIF",
  REJETE: "REJETE",
  DESACTIVE: "DESACTIVE",
});

const ARTICLE_STATUS = Object.freeze({
  BROUILLON: "BROUILLON",
  SOUMIS: "SOUMIS",
  VALIDE: "VALIDE",
  REJETE: "REJETE",
  PUBLIE: "PUBLIE",
});

const NEWS_STATUS = Object.freeze({
  BROUILLON: "BROUILLON",
  PUBLIEE: "PUBLIEE",
  ARCHIVEE: "ARCHIVEE",
});

const SUPPORT_TICKET_STATUS = Object.freeze({
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
});

const SUPPORT_TICKET_PRIORITY = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
});

const SUPPORT_TICKET_CATEGORY = Object.freeze({
  LOGIN: "LOGIN",
  ACCOUNT: "ACCOUNT",
  MESSAGING: "MESSAGING",
  NOTIFICATIONS: "NOTIFICATIONS",
  ARTICLES: "ARTICLES",
  SYSTEM: "SYSTEM",
  OTHER: "OTHER",
});

const ADMIN_ROLES = [ROLES.ADMINISTRATEUR];
const CHEF_LABO_ROLES = [ROLES.CHEF_LABO];
const EDITABLE_ARTICLE_STATUSES = [
  ARTICLE_STATUS.BROUILLON,
  ARTICLE_STATUS.SOUMIS,
  ARTICLE_STATUS.REJETE,
];

module.exports = {
  ROLES,
  ACCOUNT_STATUS,
  ARTICLE_STATUS,
  NEWS_STATUS,
  SUPPORT_TICKET_STATUS,
  SUPPORT_TICKET_PRIORITY,
  SUPPORT_TICKET_CATEGORY,
  ADMIN_ROLES,
  CHEF_LABO_ROLES,
  EDITABLE_ARTICLE_STATUSES,
};
