services:
  - type: web
    name: lr16cnstn02-backend
    runtime: docker
    dockerfilePath: ./back/Dockerfile
    dockerContext: ./back
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: FRONTEND_URL
        value: https://lr16cnstn02.vercel.app
      - key: APP_NAME
        value: Plateforme LR16CNSTN02
      - key: GEMINI_API_KEY
        sync: false
