const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

const LAB_CODE = "LR16-CNSTN-02";
const GRID_COLUMNS_DXA = [
  2641, 302, 180, 95, 142, 708, 142, 1080, 202, 1136, 284, 133, 284, 141, 469,
  98, 575, 1986,
];
const OFFICIAL_TABLE_WIDTH = GRID_COLUMNS_DXA.reduce((sum, value) => sum + value, 0) / 20;
const FONT_PATHS = {
  regular: [
    path.join(process.env.WINDIR || "C:/Windows", "Fonts", "tahoma.ttf"),
    path.join(process.env.WINDIR || "C:/Windows", "Fonts", "arial.ttf"),
  ],
  bold: [
    path.join(process.env.WINDIR || "C:/Windows", "Fonts", "tahomabd.ttf"),
    path.join(process.env.WINDIR || "C:/Windows", "Fonts", "arialbd.ttf"),
  ],
};

const LABELS = {
  fr: {
    fullName: "Nom & Prénom",
    department: "Direction/service/labo",
    date: "Date",
    justification: "Justification du besoin :",
    budgetSentence:
      "Les frais engendrés par cette demande seront imputés sur le budget du laboratoire LR16-CNSTN-02, dans le respect de la répartition approuvée, sur la rubrique",
    requestedItems: "Articles demandés",
    quantity: "Quantité",
    estimatedPrice: "Prix estimatif TTC",
    unitPrice: "Unitaire",
    total: "Total",
    attachmentsCount: "Nombre de pièces jointes",
    quote: "Devis",
    specifications: "Spécifications techniques",
    other: "Autres",
    requester: "Le demandeur",
    labHead: "Le chef du laboratoire",
    labHeadSupplement: LAB_CODE,
    dateSignature: "Date      Signature",
    technicalServices: "Avis des services techniques",
    financeControl: "Le Contrôle de Gestion",
    debNumber: "Numéro DEB",
    receivedDate: "Date de réception",
    budgetAllocation: "Imputation budgétaire",
    availabilityTitle: "Disponibilit\u00e9",
    availability: "Disponibilité     Oui     Non",
    yes: "Oui",
    no: "Non",
    signature: "Signature",
    secretaryGeneral: "Le Secrétaire Général",
    purchaseAuthorizedTitle: "Achat autoris\u00e9",
    purchaseAuthorized: "Achat autorisé :     Oui     Non     Signature",
    observations: "Observations",
    directorGeneral: "Le Directeur Général",
    approvalSignature: "Approbation et Signature",
    purchaseService: "Le Service Achat",
    purchaseRouting: "CSPF, AO…\nN° :            Date :",
    priceTtc: "Prix TTC :",
    executionNumber: "Numéro d’exécution :\nDate :",
    supplierTransmission: "Date de transmission\nau(x) fournisseur(s)",
  },
  en: {
    fullName: "Full name",
    department: "Department/service/lab",
    date: "Date",
    justification: "Need justification:",
    budgetSentence:
      "The expenses generated by this request will be charged to the budget of laboratory LR16-CNSTN-02, in accordance with the approved allocation, under the heading",
    requestedItems: "Requested items",
    quantity: "Quantity",
    estimatedPrice: "Estimated price incl. tax",
    unitPrice: "Unit price",
    total: "Total",
    attachmentsCount: "Number of attachments",
    quote: "Quote",
    specifications: "Technical specifications",
    other: "Other",
    requester: "Requester",
    labHead: "Laboratory head",
    labHeadSupplement: LAB_CODE,
    dateSignature: "Date      Signature",
    technicalServices: "Technical services opinion",
    financeControl: "Management control",
    debNumber: "DEB number",
    receivedDate: "Receipt date",
    budgetAllocation: "Budget allocation",
    availabilityTitle: "Availability",
    availability: "Availability     Yes     No",
    yes: "Yes",
    no: "No",
    signature: "Signature",
    secretaryGeneral: "Secretary General",
    purchaseAuthorizedTitle: "Purchase authorized",
    purchaseAuthorized: "Purchase authorized:     Yes     No     Signature",
    observations: "Observations",
    directorGeneral: "Director General",
    approvalSignature: "Approval and signature",
    purchaseService: "Purchasing service",
    purchaseRouting: "CSPF, AO…\nNo.:            Date:",
    priceTtc: "Price incl. tax:",
    executionNumber: "Execution number:\nDate:",
    supplierTransmission: "Transmission date\nto supplier(s)",
  },
  ar: {
    fullName: "الاسم واللقب",
    department: "الإدارة / المصلحة / المخبر",
    date: "التاريخ",
    justification: "مبرر الحاجة:",
    budgetSentence:
      "سيتم تحميل المصاريف الناتجة عن هذا الطلب على ميزانية مخبر LR16-CNSTN-02 طبقاً للتوزيع المصادق عليه ضمن البند",
    requestedItems: "المواد المطلوبة",
    quantity: "الكمية",
    estimatedPrice: "السعر التقديري مع الأداءات",
    unitPrice: "الوحدة",
    total: "المجموع",
    attachmentsCount: "عدد المرفقات",
    quote: "عرض سعر",
    specifications: "المواصفات التقنية",
    other: "أخرى",
    requester: "الطالب",
    labHead: "رئيس المخبر",
    labHeadSupplement: LAB_CODE,
    dateSignature: "التاريخ      الإمضاء",
    technicalServices: "رأي المصالح الفنية",
    financeControl: "مراقبة التصرف",
    debNumber: "رقم DEB",
    receivedDate: "تاريخ الاستلام",
    budgetAllocation: "التبويب الميزاني",
    availabilityTitle: "\u0627\u0644\u062a\u0648\u0641\u0631",
    availability: "التوفر     نعم     لا",
    yes: "\u0646\u0639\u0645",
    no: "\u0644\u0627",
    signature: "الإمضاء",
    secretaryGeneral: "الكاتب العام",
    purchaseAuthorizedTitle: "\u0627\u0644\u062a\u0631\u062e\u064a\u0635 \u0628\u0627\u0644\u0634\u0631\u0627\u0621",
    purchaseAuthorized: "الترخيص بالشراء:     نعم     لا     الإمضاء",
    observations: "ملاحظات",
    directorGeneral: "المدير العام",
    approvalSignature: "المصادقة والإمضاء",
    purchaseService: "مصلحة الشراء",
    purchaseRouting: "CSPF, AO…\nالعدد:            التاريخ:",
    priceTtc: "السعر مع الأداءات:",
    executionNumber: "رقم التنفيذ:\nالتاريخ:",
    supplierTransmission: "تاريخ الإرسال\nإلى المزوّد(ين)",
  },
};

function sanitizeText(value) {
  return String(value || "").replace(/\r\n/g, "\n").trim();
}

function normalizeLanguage(value) {
  return ["fr", "en", "ar"].includes(value) ? value : "fr";
}

function toFiniteNumber(value, fallback = 0) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : fallback;
}

function isArabicText(value) {
  return /[\u0600-\u06FF]/.test(String(value || ""));
}

function reverseRtlText(value) {
  return String(value || "")
    .split("\n")
    .map((line) => Array.from(line).reverse().join(""))
    .join("\n");
}

function formatPdfText(value, language) {
  const text = sanitizeText(value);
  if (!text) {
    return "";
  }

  if (language === "ar" || isArabicText(text)) {
    return reverseRtlText(text);
  }

  return text;
}

function resolveTextAlign(text, language, fallback = "left") {
  return language === "ar" || isArabicText(text) ? "right" : fallback;
}

function formatDate(value, language) {
  if (!value) {
    return "";
  }

  const date = value instanceof Date ? value : new Date(value);
  if (!Number.isFinite(date.getTime())) {
    return "";
  }

  const locale =
    language === "ar" ? "ar-TN" : language === "en" ? "en-US" : "fr-FR";

  return new Intl.DateTimeFormat(locale, {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(date);
}

function formatMoney(value, language) {
  const numeric = toFiniteNumber(value, 0);
  const locale =
    language === "ar" ? "ar-TN" : language === "en" ? "en-US" : "fr-TN";

  return new Intl.NumberFormat(locale, {
    minimumFractionDigits: 3,
    maximumFractionDigits: 3,
  }).format(numeric);
}

function registerFonts(doc) {
  const regular = FONT_PATHS.regular.find((candidate) => fs.existsSync(candidate));
  const bold = FONT_PATHS.bold.find((candidate) => fs.existsSync(candidate));

  if (regular) {
    doc.registerFont("LRSans", regular);
  }
  if (bold) {
    doc.registerFont("LRSans-Bold", bold);
  }

  return {
    regular: regular ? "LRSans" : "Helvetica",
    bold: bold ? "LRSans-Bold" : "Helvetica-Bold",
  };
}

function useFont(doc, fonts, weight = "regular") {
  return doc.font(weight === "bold" ? fonts.bold : fonts.regular);
}

function strokeCell(doc, x, y, width, height) {
  doc.save();
  doc.lineWidth(0.75).strokeColor("#111827").rect(x, y, width, height).stroke();
  doc.restore();
}

function drawTextBlock(doc, fonts, text, x, y, width, options = {}) {
  const {
    weight = "regular",
    fontSize = 9,
    align = "left",
    color = "#111827",
    lineGap = 0,
    height,
  } = options;

  useFont(doc, fonts, weight).fillColor(color).fontSize(fontSize).text(text || "", x, y, {
    width,
    align,
    lineGap,
    ...(height ? { height } : {}),
  });
}

function measureTextHeight(doc, fonts, text, width, options = {}) {
  const { weight = "regular", fontSize = 9, align = "left", lineGap = 0 } = options;
  useFont(doc, fonts, weight).fontSize(fontSize);
  return doc.heightOfString(text || " ", {
    width,
    align,
    lineGap,
  });
}

function buildGridWidths(maxWidth) {
  const scale = maxWidth / OFFICIAL_TABLE_WIDTH;
  return GRID_COLUMNS_DXA.map((value) => (value / 20) * scale);
}

function widthsFromSpans(gridWidths, spans) {
  let index = 0;
  return spans.map((span) => {
    const width = gridWidths.slice(index, index + span).reduce((sum, value) => sum + value, 0);
    index += span;
    return width;
  });
}

function drawTextInCell(doc, fonts, text, x, y, width, height, language, options = {}) {
  const {
    weight = "regular",
    fontSize = 8.8,
    align = "center",
    color = "#111827",
    lineGap = 0,
    padding = 5,
    valign = "middle",
  } = options;

  const prepared = formatPdfText(text, language);
  if (!prepared) {
    return;
  }

  const resolvedAlign =
    align === "auto" ? resolveTextAlign(prepared, language, language === "ar" ? "right" : "left") : align;
  const availableWidth = Math.max(0, width - padding * 2);
  const textHeight = measureTextHeight(doc, fonts, prepared, availableWidth, {
    weight,
    fontSize,
    align: resolvedAlign,
    lineGap,
  });
  const textY = valign === "middle" ? y + Math.max(4, (height - textHeight) / 2) : y + padding;

  drawTextBlock(doc, fonts, prepared, x + padding, textY, availableWidth, {
    weight,
    fontSize,
    align: resolvedAlign,
    color,
    lineGap,
    height: Math.max(0, height - (textY - y) - padding),
  });
}

function drawFieldCell(doc, fonts, label, value, x, y, width, height, language) {
  strokeCell(doc, x, y, width, height);

  drawTextInCell(doc, fonts, label, x, y + 2, width, 12, language, {
    weight: "bold",
    fontSize: 8.6,
    align: "center",
    padding: 4,
    valign: "middle",
  });

  const preparedValue = formatPdfText(value, language);
  drawTextInCell(doc, fonts, preparedValue, x, y + 14, width, height - 16, language, {
    fontSize: 8.9,
    align: resolveTextAlign(preparedValue, language, language === "ar" ? "right" : "left"),
    padding: 5,
    valign: "top",
  });
}

function drawVerticalSeparator(doc, x, y, height) {
  doc.save();
  doc
    .lineWidth(0.55)
    .strokeColor("#111827")
    .moveTo(x, y)
    .lineTo(x, y + height)
    .stroke();
  doc.restore();
}

function drawCaptionInArea(doc, fonts, label, x, y, width, language, options = {}) {
  const {
    weight = "regular",
    fontSize = 8.1,
    align = "center",
    padding = 4,
    maxHeight = 14,
    lineGap = 0.5,
  } = options;
  const prepared = formatPdfText(label, language);
  if (!prepared) {
    return;
  }

  drawTextBlock(doc, fonts, prepared, x + padding, y + 3, Math.max(0, width - padding * 2), {
    weight,
    fontSize,
    align: align === "auto" ? resolveTextAlign(prepared, language, language === "ar" ? "right" : "left") : align,
    lineGap,
    height: maxHeight,
  });
}

function drawBlankCaptionCell(doc, fonts, label, x, y, width, height, language, options = {}) {
  strokeCell(doc, x, y, width, height);
  drawCaptionInArea(doc, fonts, label, x, y, width, language, options);
}

function measureInlineTextWidth(doc, fonts, text, language, options = {}) {
  const { weight = "regular", fontSize = 8.2 } = options;
  const prepared = formatPdfText(text, language);
  useFont(doc, fonts, weight).fontSize(fontSize);
  return doc.widthOfString(prepared || "");
}

function drawCheckboxSquare(doc, x, y, size = 8) {
  doc.save();
  doc.lineWidth(0.7).strokeColor("#111827").rect(x, y, size, size).stroke();
  doc.restore();
}

function drawCheckboxOptions(doc, fonts, labels, x, y, width, language, options = {}) {
  const { fontSize = 8.1, boxSize = 8, itemGap = 16, weight = "regular" } = options;
  const prepared = labels.map((label) => formatPdfText(label, language));
  useFont(doc, fonts, weight).fontSize(fontSize);
  const optionWidths = prepared.map((label) => boxSize + 4 + doc.widthOfString(label || ""));
  const totalWidth =
    optionWidths.reduce((sum, value) => sum + value, 0) + itemGap * Math.max(0, labels.length - 1);
  let cursorX = x + Math.max(4, (width - totalWidth) / 2);

  prepared.forEach((label, index) => {
    drawCheckboxSquare(doc, cursorX, y, boxSize);
    drawTextBlock(doc, fonts, label, cursorX + boxSize + 4, y - 1, optionWidths[index] - boxSize - 4 + 2, {
      weight,
      fontSize,
      align: "left",
      height: boxSize + 4,
    });
    cursorX += optionWidths[index] + itemGap;
  });
}

function drawSplitEntryCell(doc, fonts, labels, x, y, width, height, language, options = {}) {
  const ratios = Array.isArray(options.ratios) && options.ratios.length ? options.ratios : [0.42, 0.58];
  strokeCell(doc, x, y, width, height);

  let cursorX = x;
  labels.forEach((label, index) => {
    const currentWidth =
      index === labels.length - 1
        ? x + width - cursorX
        : Math.round(width * (ratios[index] || 0));

    if (index > 0) {
      drawVerticalSeparator(doc, cursorX, y, height);
    }

    drawCaptionInArea(doc, fonts, label, cursorX, y, currentWidth, language, {
      weight: index === 0 ? "regular" : "regular",
      fontSize: 8.05,
      align: "center",
    });
    cursorX += currentWidth;
  });
}

function drawChoiceCell(doc, fonts, title, optionLabels, x, y, width, height, language) {
  strokeCell(doc, x, y, width, height);
  const titleWidth = Math.round(width * 0.46);
  drawVerticalSeparator(doc, x + titleWidth, y, height);

  drawTextInCell(doc, fonts, title, x, y, titleWidth, height, language, {
    fontSize: 8.05,
    align: "center",
    padding: 4,
    valign: "middle",
  });

  const optionsY = y + Math.max(6, (height - 8) / 2);
  drawCheckboxOptions(doc, fonts, optionLabels, x + titleWidth + 2, optionsY, width - titleWidth - 4, language, {
    fontSize: 8.1,
    boxSize: 8,
    itemGap: 14,
  });
}

function drawApprovalChoiceCell(doc, fonts, title, yesLabel, noLabel, signatureLabel, x, y, width, height, language) {
  strokeCell(doc, x, y, width, height);
  const titleWidth = Math.round(width * 0.37);
  const optionsWidth = Math.round(width * 0.29);
  const signatureX = x + titleWidth + optionsWidth;
  const signatureWidth = x + width - signatureX;

  drawVerticalSeparator(doc, x + titleWidth, y, height);
  drawVerticalSeparator(doc, signatureX, y, height);

  drawTextInCell(doc, fonts, title, x, y, titleWidth, height, language, {
    fontSize: 8.0,
    align: "center",
    padding: 4,
    valign: "middle",
  });

  drawCheckboxOptions(doc, fonts, [yesLabel, noLabel], x + titleWidth + 3, y + Math.max(8, (height - 8) / 2), optionsWidth - 6, language, {
    fontSize: 8.0,
    boxSize: 8,
    itemGap: 12,
  });

  drawCaptionInArea(doc, fonts, signatureLabel, signatureX, y, signatureWidth, language, {
    fontSize: 8.0,
    align: "center",
  });
}

function drawStructuredInfoCell(doc, fonts, text, x, y, width, height, language, options = {}) {
  strokeCell(doc, x, y, width, height);
  drawTextInCell(doc, fonts, text, x, y, width, height, language, {
    fontSize: options.fontSize || 7.95,
    align: options.align || "left",
    padding: options.padding || 4,
    valign: "top",
    lineGap: options.lineGap || 0.8,
  });
}

function drawSimpleRow(doc, fonts, x, y, gridWidths, spans, height, texts, language, options = {}) {
  const widths = widthsFromSpans(gridWidths, spans);
  const aligns = options.aligns || [];
  const weights = options.weights || [];
  const fontSizes = options.fontSizes || [];
  const colors = options.colors || [];
  const paddings = options.paddings || [];
  const valigs = options.valigns || [];
  const lineGaps = options.lineGaps || [];

  let cursorX = x;
  widths.forEach((width, index) => {
    strokeCell(doc, cursorX, y, width, height);
    drawTextInCell(doc, fonts, texts[index] || "", cursorX, y, width, height, language, {
      align: aligns[index] || "center",
      weight: weights[index] || "regular",
      fontSize: fontSizes[index] || 8.7,
      color: colors[index] || "#111827",
      padding: paddings[index] || 5,
      valign: valigs[index] || "middle",
      lineGap: lineGaps[index] || 0,
    });
    cursorX += width;
  });

  return y + height;
}

function drawIdentityRow(doc, fonts, labels, x, y, gridWidths, data, language) {
  const spans = [3, 13, 2];
  const widths = widthsFromSpans(gridWidths, spans);
  const values = [
    data.demandeurNomPrenom,
    data.directionServiceLabo,
    formatDate(data.dateDemande, language),
  ];
  const maxValueHeight = Math.max(
    ...values.map((value, index) =>
      measureTextHeight(doc, fonts, formatPdfText(value, language), Math.max(0, widths[index] - 10), {
        fontSize: 8.9,
        align: resolveTextAlign(value, language, language === "ar" ? "right" : "left"),
      }),
    ),
  );
  const rowHeight = Math.max(38, 18 + maxValueHeight + 7);

  let cursorX = x;
  const titles = [labels.fullName, labels.department, labels.date];
  widths.forEach((width, index) => {
    drawFieldCell(doc, fonts, titles[index], values[index], cursorX, y, width, rowHeight, language);
    cursorX += width;
  });

  return y + rowHeight;
}

function drawJustificationRow(doc, fonts, labels, x, y, tableWidth, data, language) {
  const text = formatPdfText(data.justificationBesoin, language);
  const bodyHeight = measureTextHeight(doc, fonts, text || " ", tableWidth - 12, {
    fontSize: 8.9,
    align: resolveTextAlign(text, language, language === "ar" ? "right" : "left"),
    lineGap: 1,
  });
  const rowHeight = Math.max(52, 18 + bodyHeight + 10);

  strokeCell(doc, x, y, tableWidth, rowHeight);
  drawTextInCell(doc, fonts, labels.justification, x, y + 1, tableWidth, 14, language, {
    weight: "bold",
    fontSize: 8.8,
    align: language === "ar" ? "right" : "left",
    padding: 5,
    valign: "middle",
  });
  drawTextInCell(doc, fonts, text, x, y + 14, tableWidth, rowHeight - 16, language, {
    fontSize: 8.9,
    align: resolveTextAlign(text, language, language === "ar" ? "right" : "left"),
    padding: 5,
    valign: "top",
    lineGap: 1,
  });

  return y + rowHeight;
}

function drawBudgetSentenceRow(doc, fonts, labels, x, y, tableWidth, data, language) {
  const rubrique = sanitizeText(data.rubriqueLabel) || "………………………………";
  const sentence = `${labels.budgetSentence} ${rubrique}`;
  const prepared = formatPdfText(sentence, language);
  const rowHeight = Math.max(
    28,
    measureTextHeight(doc, fonts, prepared, tableWidth - 12, {
      weight: "regular",
      fontSize: 8.6,
      align: resolveTextAlign(prepared, language, language === "ar" ? "right" : "left"),
      lineGap: 1,
    }) + 10,
  );

  strokeCell(doc, x, y, tableWidth, rowHeight);
  drawTextInCell(doc, fonts, prepared, x, y, tableWidth, rowHeight, language, {
    fontSize: 8.6,
    align: resolveTextAlign(prepared, language, language === "ar" ? "right" : "left"),
    color: "#b91c1c",
    padding: 5,
    valign: "middle",
    lineGap: 1,
  });

  return y + rowHeight;
}

function drawItemsHeader(doc, fonts, labels, x, y, gridWidths, language) {
  const topSpans = [9, 1, 8];
  const bottomSpans = [9, 1, 7, 1];
  const topHeights = 18;
  const bottomHeight = 17;

  y = drawSimpleRow(
    doc,
    fonts,
    x,
    y,
    gridWidths,
    topSpans,
    topHeights,
    [labels.requestedItems, labels.quantity, labels.estimatedPrice],
    language,
    {
      aligns: ["center", "center", "center"],
      weights: ["bold", "bold", "bold"],
      fontSizes: [8.5, 8.5, 8.5],
    },
  );

  y = drawSimpleRow(
    doc,
    fonts,
    x,
    y,
    gridWidths,
    bottomSpans,
    bottomHeight,
    ["", "", labels.unitPrice, labels.total],
    language,
    {
      aligns: ["center", "center", "center", "center"],
      weights: ["regular", "regular", "bold", "bold"],
      fontSizes: [8.3, 8.3, 8.3, 8.3],
    },
  );

  return {
    rowY: y,
    columns: widthsFromSpans(gridWidths, bottomSpans),
  };
}

function drawItemRow(doc, fonts, x, y, columns, line, index, language) {
  const article = `${index + 1}- ${sanitizeText(line?.articleService)}`.trim();
  const articleText = formatPdfText(article, language);
  const quantity = toFiniteNumber(line?.quantite, 0);
  const unitPrice = toFiniteNumber(line?.prixUnitaireTtc, 0);
  const lineTotal = toFiniteNumber(line?.totalLigne, quantity * unitPrice);
  const rowHeight = Math.max(
    24,
    measureTextHeight(doc, fonts, articleText, Math.max(0, columns[0] - 10), {
      fontSize: 8.8,
      align: resolveTextAlign(articleText, language, language === "ar" ? "right" : "left"),
      lineGap: 1,
    }) + 8,
  );

  let cursorX = x;
  const texts = [
    articleText,
    quantity ? String(quantity) : "",
    unitPrice ? formatMoney(unitPrice, language) : formatMoney(0, language),
    lineTotal ? formatMoney(lineTotal, language) : formatMoney(0, language),
  ];
  const aligns = [
    resolveTextAlign(articleText, language, language === "ar" ? "right" : "left"),
    "center",
    "right",
    "right",
  ];

  columns.forEach((width, indexCell) => {
    strokeCell(doc, cursorX, y, width, rowHeight);
    drawTextInCell(doc, fonts, texts[indexCell], cursorX, y, width, rowHeight, language, {
      fontSize: 8.8,
      align: aligns[indexCell],
      padding: 5,
      valign: indexCell === 0 ? "top" : "middle",
      lineGap: indexCell === 0 ? 1 : 0,
    });
    cursorX += width;
  });

  return y + rowHeight;
}

function drawTotalRow(doc, fonts, labels, x, y, gridWidths, totalGeneral, language) {
  return drawSimpleRow(
    doc,
    fonts,
    x,
    y,
    gridWidths,
    [10, 7, 1],
    22,
    ["", labels.total, formatMoney(totalGeneral, language)],
    language,
    {
      aligns: ["center", "center", "right"],
      weights: ["regular", "bold", "bold"],
      fontSizes: [8.6, 8.8, 8.8],
      paddings: [5, 5, 6],
    },
  );
}

function checkbox(checked) {
  return checked ? "[x]" : "[ ]";
}

function drawAttachmentsRow(doc, fonts, labels, x, y, gridWidths, data, language) {
  const selected = new Set(Array.isArray(data.typesPiecesJointes) ? data.typesPiecesJointes : []);
  const otherText = sanitizeText(data.autrePieceJointe);
  const rowTexts = [
    `${labels.attachmentsCount} : ${Number(data.nombrePiecesJointes || 0)}`,
    `${checkbox(selected.has("DEVIS"))} ${labels.quote}`,
    `${checkbox(selected.has("SPECIFICATIONS_TECHNIQUES"))} ${labels.specifications}`,
    `${checkbox(selected.has("AUTRES"))} ${labels.other}${otherText ? ` : ${otherText}` : ""}`,
  ];
  const widths = widthsFromSpans(gridWidths, [4, 3, 5, 6]);
  const rowHeight = Math.max(
    24,
    ...rowTexts.map((text, index) =>
      measureTextHeight(doc, fonts, formatPdfText(text, language), Math.max(0, widths[index] - 10), {
        fontSize: 8.4,
        align: index === 0 ? resolveTextAlign(text, language, language === "ar" ? "right" : "left") : "left",
        lineGap: 1,
      }) + 8,
    ),
  );

  return drawSimpleRow(doc, fonts, x, y, gridWidths, [4, 3, 5, 6], rowHeight, rowTexts, language, {
    aligns: [
      resolveTextAlign(rowTexts[0], language, language === "ar" ? "right" : "left"),
      "left",
      "left",
      "left",
    ],
    fontSizes: [8.4, 8.4, 8.4, 8.4],
    paddings: [5, 5, 5, 5],
    valigs: ["middle", "middle", "middle", "middle"],
    lineGaps: [1, 1, 1, 1],
  });
}

function drawAdministrationBlocks(doc, fonts, labels, x, y, gridWidths, language) {
  const row1Height = 44;
  const row2Height = 32;
  const row3Height = 38;
  const row4Height = 40;
  const row5Height = 28;
  const row6Height = 46;
  const row7Height = 28;
  const row8Height = 46;
  const row9Height = 38;
  const row10Height = 48;

  let cursorX = x;
  let widths = widthsFromSpans(gridWidths, [2, 9, 7]);
  drawBlankCaptionCell(doc, fonts, labels.requester, cursorX, y, widths[0], row1Height, language, {
    weight: "bold",
    fontSize: 8.3,
  });
  cursorX += widths[0];
  drawBlankCaptionCell(
    doc,
    fonts,
    `${labels.labHead}\n${labels.labHeadSupplement}`,
    cursorX,
    y,
    widths[1],
    row1Height,
    language,
    {
      weight: "bold",
      fontSize: 8.25,
      lineGap: 0.8,
      maxHeight: 20,
    },
  );
  cursorX += widths[1];
  drawSplitEntryCell(doc, fonts, [labels.date, labels.signature], cursorX, y, widths[2], row1Height, language, {
    ratios: [0.36, 0.64],
  });
  y += row1Height;

  y = drawSimpleRow(doc, fonts, x, y, gridWidths, [18], row2Height, [labels.technicalServices], language, {
    aligns: ["center"],
    weights: ["bold"],
    fontSizes: [8.85],
  });

  cursorX = x;
  widths = widthsFromSpans(gridWidths, [5, 8, 5]);
  drawBlankCaptionCell(doc, fonts, labels.debNumber, cursorX, y, widths[0], row3Height, language, {
    fontSize: 8.1,
  });
  cursorX += widths[0];
  drawBlankCaptionCell(doc, fonts, labels.financeControl, cursorX, y, widths[1], row3Height, language, {
    weight: "bold",
    fontSize: 8.25,
  });
  cursorX += widths[1];
  drawBlankCaptionCell(doc, fonts, labels.receivedDate, cursorX, y, widths[2], row3Height, language, {
    fontSize: 8.1,
  });
  y += row3Height;

  cursorX = x;
  widths = widthsFromSpans(gridWidths, [6, 8, 4]);
  drawBlankCaptionCell(doc, fonts, labels.budgetAllocation, cursorX, y, widths[0], row4Height, language, {
    fontSize: 8.05,
  });
  cursorX += widths[0];
  drawChoiceCell(doc, fonts, labels.availabilityTitle || labels.availability, [labels.yes, labels.no], cursorX, y, widths[1], row4Height, language);
  cursorX += widths[1];
  drawBlankCaptionCell(doc, fonts, labels.signature, cursorX, y, widths[2], row4Height, language, {
    fontSize: 8.15,
  });
  y += row4Height;

  y = drawSimpleRow(doc, fonts, x, y, gridWidths, [18], row5Height, [labels.secretaryGeneral], language, {
    aligns: ["center"],
    weights: ["bold"],
    fontSizes: [8.85],
  });

  cursorX = x;
  widths = widthsFromSpans(gridWidths, [6, 12]);
  drawApprovalChoiceCell(
    doc,
    fonts,
    labels.purchaseAuthorizedTitle || labels.purchaseAuthorized,
    labels.yes,
    labels.no,
    labels.signature,
    cursorX,
    y,
    widths[0],
    row6Height,
    language,
  );
  cursorX += widths[0];
  drawBlankCaptionCell(doc, fonts, labels.observations, cursorX, y, widths[1], row6Height, language, {
    fontSize: 8.15,
  });
  y += row6Height;

  y = drawSimpleRow(doc, fonts, x, y, gridWidths, [18], row7Height, [labels.directorGeneral], language, {
    aligns: ["center"],
    weights: ["bold"],
    fontSizes: [8.85],
  });

  cursorX = x;
  widths = widthsFromSpans(gridWidths, [6, 12]);
  drawBlankCaptionCell(doc, fonts, labels.approvalSignature, cursorX, y, widths[0], row8Height, language, {
    fontSize: 8.1,
    lineGap: 0.8,
  });
  cursorX += widths[0];
  drawBlankCaptionCell(doc, fonts, labels.observations, cursorX, y, widths[1], row8Height, language, {
    fontSize: 8.15,
  });
  y += row8Height;

  cursorX = x;
  widths = widthsFromSpans(gridWidths, [5, 8, 5]);
  strokeCell(doc, cursorX, y, widths[0], row9Height);
  cursorX += widths[0];
  drawBlankCaptionCell(doc, fonts, labels.purchaseService, cursorX, y, widths[1], row9Height, language, {
    weight: "bold",
    fontSize: 8.25,
  });
  cursorX += widths[1];
  drawBlankCaptionCell(doc, fonts, labels.receivedDate, cursorX, y, widths[2], row9Height, language, {
    fontSize: 8.1,
  });
  y += row9Height;

  cursorX = x;
  widths = widthsFromSpans(gridWidths, [1, 7, 7, 3]);
  drawStructuredInfoCell(doc, fonts, labels.purchaseRouting, cursorX, y, widths[0], row10Height, language, {
    fontSize: 7.85,
    padding: 4,
    lineGap: 0.8,
  });
  cursorX += widths[0];
  drawStructuredInfoCell(doc, fonts, labels.priceTtc, cursorX, y, widths[1], row10Height, language, {
    fontSize: 8.15,
    padding: 5,
  });
  cursorX += widths[1];
  drawStructuredInfoCell(doc, fonts, labels.executionNumber, cursorX, y, widths[2], row10Height, language, {
    fontSize: 8.0,
    padding: 5,
    lineGap: 0.8,
  });
  cursorX += widths[2];
  drawStructuredInfoCell(doc, fonts, labels.supplierTransmission, cursorX, y, widths[3], row10Height, language, {
    fontSize: 7.75,
    align: "center",
    padding: 4,
    lineGap: 0.8,
  });

  return y + row10Height;
}

function administrationBlockHeight() {
  return 44 + 32 + 38 + 40 + 28 + 46 + 28 + 46 + 38 + 48;
}

async function buildPurchaseExpressionPdf(data) {
  return new Promise((resolve, reject) => {
    const language = normalizeLanguage(data.language);
    const labels = LABELS[language];
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 30, right: 24, bottom: 24, left: 24 },
      info: {
        Title: `Expression de besoins ${data.reference || ""}`.trim(),
        Author: "Plateforme LR16-CNSTN-02",
      },
    });

    const fonts = registerFonts(doc);
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const bottomLimit = doc.page.height - doc.page.margins.bottom;
    const availableWidth = pageWidth - doc.page.margins.left - doc.page.margins.right;
    const tableWidth = Math.min(OFFICIAL_TABLE_WIDTH, availableWidth);
    const gridWidths = buildGridWidths(tableWidth);
    const left = (pageWidth - tableWidth) / 2;
    const top = doc.page.margins.top;

    let y = top;
    y = drawIdentityRow(doc, fonts, labels, left, y, gridWidths, data, language);
    y = drawJustificationRow(doc, fonts, labels, left, y, tableWidth, data, language);
    y = drawBudgetSentenceRow(doc, fonts, labels, left, y, tableWidth, data, language);

    let header = drawItemsHeader(doc, fonts, labels, left, y, gridWidths, language);
    y = header.rowY;

    const itemColumns = header.columns;
    const lines = Array.isArray(data.lignes) ? data.lignes : [];

    lines.forEach((line, index) => {
      const previewText = formatPdfText(`${index + 1}- ${sanitizeText(line?.articleService)}`.trim(), language);
      const previewHeight = Math.max(
        24,
        measureTextHeight(doc, fonts, previewText, Math.max(0, itemColumns[0] - 10), {
          fontSize: 8.8,
          align: resolveTextAlign(previewText, language, language === "ar" ? "right" : "left"),
          lineGap: 1,
        }) + 8,
      );

      if (y + previewHeight > bottomLimit - 18) {
        doc.addPage();
        y = top;
        header = drawItemsHeader(doc, fonts, labels, left, y, gridWidths, language);
        y = header.rowY;
      }

      y = drawItemRow(doc, fonts, left, y, header.columns, line, index, language);
    });

    const trailingReserve = 22 + 28 + administrationBlockHeight();
    if (y + trailingReserve > bottomLimit) {
      doc.addPage();
      y = top;
    }

    y = drawTotalRow(doc, fonts, labels, left, y, gridWidths, data.totalGeneral, language);
    y = drawAttachmentsRow(doc, fonts, labels, left, y, gridWidths, data, language);

    if (y + administrationBlockHeight() > bottomLimit) {
      doc.addPage();
      y = top;
    }

    drawAdministrationBlocks(doc, fonts, labels, left, y, gridWidths, language);
    doc.end();
  });
}

module.exports = {
  buildPurchaseExpressionPdf,
};
